added files that are formatted using VS code 'automatically'
deepak-sharma-ta/mle-training pull request #6
Opened 2023-03-22 10:16 UTC by deepak-sharma-ta

Closes #5 

```
{
    "python.linting.enabled": true,
    "python.linting.lintOnSave": true,
    "python.linting.flake8Enabled": true,
    "editor.formatOnSave": true,
    "python.formatting.provider": "black"
}
```

2023-03-22 13:37 UTC, vinayksoni requested changes

2023-03-22 13:37 UTC, vinayksoni commented on .vscode/settings.json
> +    "python.formatting.provider": "black"
add line parameter as well

2023-03-23 09:39 UTC, deepak-sharma-ta commented on .vscode/settings.json
> +    "python.formatting.provider": "black"
done

2023-03-24 04:26 UTC, vinayksoni approved these changes

2023-03-24 05:09 UTC, merged